{
    'name': 'New Life hospital',
    'version': '1.0',
    'summary': 'taking care of life, this is the New journey New Life',
    'description': 'we are responsible of your life',
    'category': 'hospital/New Life hospital',
    'author': 'Ganu Reddy ',
    'website': 'www.newlifehospital.com',
    'license': 'LGPL-3',
    'depends': ['base', 'mail'],
    'data': [
        'views/patient.xml',
        'views/kids.xml',
        'views/patient_gender.xml',
        'views/menu.xml',
        'views/appointment.xml',
        'security/ir.model.access.csv',
        'data/data.xml',
    ],
    'demo': [''],
    'installable': True,
    'images': ['static/description/icon.png'],
    'auto_install': False,
    'application': True,
}