{
    'name': 'MSC',
    'version': '1.0',
    'summary': 'nothing',
    'description': 'nothing',
    'category': 'member/MSC',
    'author': '',
    'website': '',
    'license': 'LGPL-3',
    'depends': ['base', 'mail'],
    'data': [
        'reports/report.xml',
        'reports/subscription_contacts.xml',
        'views/my_contact_subscription.xml',
        'views/my_subscription.xml',
        'views/my_payment.xml',
        'views/my_transaction.xml',
        'security/ir.model.access.csv',
        'data/subscription_mail_template.xml',
    ],
    'demo': [''],
    'installable': True,
    'images': ['static/description/icon.png'],
    'auto_install': False,
    'application': True,
}
